# Generated by Django 2.2.4 on 2021-04-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dojo_ninja', '0002_dojos_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojos',
            name='desc',
        ),
        migrations.AddField(
            model_name='dojos',
            name='description',
            field=models.CharField(default='dojo antiguo', max_length=255),
        ),
    ]
